version: "3"
services:
  web.service:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: web-container
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    tty: true
