<template>
  <div>
    <h2>このサイトについて</h2>
    <section>
      <h3>動作環境について</h3>
        <p>当サイトは以下の環境での動作を確認しています。</p>
        <dl>
          <dt>OS</dt>
          <dd>Mac</dd>
        </dl>
        <dl>
          <dt>ブラウザ</dt>
          <dd>Google Chrome</dd>
        </dl>
        <p>いずれもブラウザの設定でCSSとJavaScriptが有効な状態になっているものとします。</p>
    </section>
    <section>
      <h3>ご利用について</h3>
      <p>当サイトのご利用については自己責任でお願いします。</p>
    </section>
    <section>
      <h3>お問い合わせ</h3>
      <address>
        <p>下記メールアドレスよりお問い合わせください。</p>
        <p>&#109;&#97;&#107;es&#113;&#108;&#64;&#103;&#109;&#97;&#105;l&#46;c&#111;m</p>
      </address>
    </section>
  </div>
</template>
